version: '3.9'

services:
  api: &api
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: omnihr-api
    command: python main.py
    volumes:
      - ../..:/app
      - ../../data/employees.db:/app/data/employees.db
    ports:
      - '8000:8000'
    env_file:
      - ../../.env.development
    restart: on-failure
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../../redis:/data

volumes:
  redis:
